---
- include: call_script.yml
  vars:
    script_name: update_admin_password
    args:
      new_password: "{{ nexus_admin_password }}"

- name: "Admin password changed: {{ nexus_admin_password }}"
  set_fact:
    current_nexus_admin_password: "{{ nexus_admin_password }}"
  no_log: true
