---
# roles/ansible-role-nexus/tasks/debug-playbook-vars.yml

# Debug other values or specific values you want printed last


- name: "Debug - ansible playbook variable values"
  debug: msg="{{ vars }}"
  when: ansible-role-nexus_debug


- name: "Debug value of playbook vars"
  debug: msg="{{ vars | to_yaml }}"
  when: ansible-role-nexus_debug
