---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
  options:
    config-file: .ansible-lint
platforms:
  - name: role_nexus-default-xenial
    source:
      alias: ubuntu/xenial/amd64
  - name: role_nexus-default-eon
    source:
      type: image
      alias: ubuntu/eon/amd64
  - name: role_nexus-default-disco
    source:
      type: image
      alias: ubuntu/disco/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
